# Generated by Django 6.1.2 on 2026-10-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('size', models.CharField(max_length=20, verbose_name='Розмір')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
            ],
        ),
    ]
